spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5438/payment_db
    username: payment_user
    password: payment_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080

iyzico:
  api-key: sandbox-WlfGvI55L7mxfHobUicOPJQAJir7lP9B
  secret-key: sandbox-QLhnPcR9PwppAdWNspNrVAzSK6IiqL36
  base-url: https://sandbox-api.iyzipay.com
