spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5438/payment_db
    username: payment_user
    password: payment_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080

iyzico:
  api-key: SANDBOX_API_KEY
  secret-key: SANDBOX_SECRET_KEY
  base-url: https://sandbox-api.iyzipay.com
